language: python

sudo: false   # use container-based infrastructure

matrix:
  include:
    - python: '3.6'
      env: ORANGE="3.16.0"

    - python: '3.6'
      env: ORANGE="release"

    - python: '3.6'
      env: ORANGE="master"

cache:
    apt: true   # does not work for public repos
    pip: true

before_install:
    - pip install -U setuptools pip wheel
    - pip install codecov

install:
    - pip install PyQt5==5.11.*
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - travis_wait pip install -r requirements.txt
    - pip install -e .

script:
    - export XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" python setup.py test

after_success:
    - codecov
